"""Optional live Groq check and small documented demonstration.

Run with GROQ_MODEL set and a local GROQ_API_KEY in .env. This intentionally
uses the real provider; the regular unit suite never needs network access.
"""

import json
import os
from pathlib import Path

from app import create_app
from stylometry import analyze_text


# Generated by Codex for this project's evaluation on 2026-10-07.
AI_REGULAR = (
    'The garden offered a gentle reminder that every season brings a chance to begin again, '
    'and the path invited us to move forward with patience and hope. '
    'The garden offered a quiet reminder that every morning brings a chance to begin again, '
    'and the path invited us to move forward with patience and hope. '
    'The garden offered a simple reminder that every evening brings a chance to begin again, '
    'and the path invited us to move forward with patience and hope.'
)

# Generated by Codex for this project's evaluation on 2026-10-07.
AI_IRREGULAR = (
    'I dunno why the clock clicked twice, then quit. Anyway, Mara said the moon looked '
    'like a bruised peach; I laughed, missed the bus, and got soaked. Later I scribbled '
    'a map on a grocery receipt, crossed half of it out, and walked home by the river. '
    'Nothing dramatic happened there, unless you count the old dog that followed me '
    'for three blocks.'
)

# Charlotte Perkins Gilman, The Yellow Wallpaper, 1892.
# https://www.gutenberg.org/cache/epub/1952/pg1952-images.html
HUMAN_GILMAN = (
    'It is very seldom that mere ordinary people like John and myself secure ancestral halls '
    'for the summer. A colonial mansion, a hereditary estate, I would say a haunted house, '
    'and reach the height of romantic felicity—but that would be asking too much of fate! '
    'Still I will proudly declare that there is something queer about it. '
    'Else, why should it be let so cheaply? And why have stood so long untenanted?'
)

# Codex assembled this mixed-source passage from the cited Gilman excerpt
# and its own AI_REGULAR text. This is mixed source, not human-edited AI.
MIXED_SOURCE = HUMAN_GILMAN + ' ' + AI_REGULAR

# Generated by Codex for this project's evaluation on 2026-10-07.
AI_POETRY = (
    'I carried a lantern across the square\n'
    'I carried a lantern through morning air\n'
    'I carried a lantern where cold bells rang\n'
    'I carried a lantern while sparrows sang\n'
    'I carried a lantern beyond the gate\n'
    'I carried a lantern and chose to wait\n'
    'I carried a lantern along the shore\n'
    'I carried a lantern and wanted more\n'
    'I carried a lantern until the rain\n'
    'I carried a lantern and came again'
)

# Generated by Codex for this project's evaluation on 2026-10-07.
AI_CODE_SWITCHED = (
    'Anoche the street was quiet, pero I could hear the baker opening his shop before dawn. '
    'I walked toward the plaza con mi cuaderno, hoping to remember the dream that had woken me. '
    'The fountain was empty, y una señora told me the water had been turned off for repairs. '
    'I thanked her and kept walking, because the dream was fading faster than the light arrived.'
)


def speech_cases():
    """Load speech excerpts supplied locally; do not redistribute transcripts."""
    cases = []
    for variable, name in (('MLK_SPEECH_PATH', 'human_mlk_dream'),
                           ('MALCOLM_SPEECH_PATH', 'human_malcolm_ballot_bullet')):
        path = os.getenv(variable)
        if path:
            cases.append((name, Path(path).read_text(encoding='utf-8')))
    return cases


def run():
    # This batch compares detector outputs; the separate rate-limit test checks 429s.
    app = create_app({'RATELIMIT_ENABLED': False})
    client = app.test_client()
    cases = [('ai_regular', AI_REGULAR), ('human_gilman', HUMAN_GILMAN),
             ('ai_irregular', AI_IRREGULAR), ('mixed_source', MIXED_SOURCE),
             ('ai_poetry', AI_POETRY), ('ai_code_switched', AI_CODE_SWITCHED),
             *speech_cases()]
    content_ids = {}
    for name, text in cases:
        metrics = analyze_text(text)['measurements']
        response = client.post('/submit', json={'creator_id': f'demo-{name}', 'text': text})
        print(json.dumps({'case': name, 'word_count': metrics['word_count'],
                          'sentence_count': metrics['sentence_count'],
                          'http_status': response.status_code, 'response': response.json}))
        if response.status_code != 200:
            raise SystemExit('Live submission did not succeed; inspect the response above.')
        content_ids[name] = response.json['content_id']
    appeal = client.post('/appeal', json={
        'content_id': content_ids['ai_irregular'],
        'creator_id': 'demo-ai_irregular',
        'creator_reasoning': 'Demo appeal to verify that the original decision remains unchanged.'})
    print(json.dumps({'case': 'demo_appeal', 'http_status': appeal.status_code,
                      'response': appeal.json}))


if __name__ == '__main__':
    run()
